name: Deploy app to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: ${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "v0.113.0"
          extended: true

      - name: Build
        shell: bash
        run: hugo --gc --minify

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Deploy dApp to S3
        shell: bash
        env:
          S3_ACCOUNT_NAME: ${{ secrets.S3_ACCOUNT_NAME }}
        run: |
          cd public
          aws s3 sync . s3://${S3_ACCOUNT_NAME}

      - name: Invalidate CloudFront cache
        shell: bash
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
